services:
  nestjs-app:
    build:
      context: student-record-backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=root_passowrd_123
      - MYSQL_DATABASE=student_record_db
      - MYSQL_USER=muaz
      - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3307

  react-app:
    build:
      context: student-record-frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - nestjs-app
    environment:
      - VITE_API_URL=http://localhost:3000
