FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173

CMD ["npx", "serve", "-s", "build"]
