# Use official PostgreSQL image as the base image
FROM postgres:16-alpine

# Set environment variables
ENV POSTGRES_USER muaz
ENV POSTGRES_PASSWORD 1234
ENV POSTGRES_DB student_record_dev

# Expose PostgreSQL port
EXPOSE 5432